.PHONY: shell
shell:
	docker-compose exec laravel-octane-php-fpm-nginx bash

.PHONY: run
run:
	docker-compose up -d

.PHONY: stop
stop:
	docker-compose stop

.PHONY: build
build:
	docker-compose build
