[entryPoints]
    [entryPoints.http]
        address = ":80"

[api]
    insecure = true
    dashboard = true

[providers]
    [providers.docker]
        network = "traefik-octane-test-proxy"
        exposedByDefault = false
