version: "3.8"

networks:
    traefik-octane-test-proxy:
        external: true

services:
    traefik-octane-test-proxy:
        image: traefik:v2.4
        container_name: traefik-octane-test-proxy-container
        restart: unless-stopped
        networks:
            - traefik-octane-test-proxy
        ports:
            # dashboard
            - ${TRAEFIK_DASHBOARD_HOST_PORT}:8080
            # web
            - ${TRAEFIK_HTTP_ENTRYPOINT_HOST_PORT}:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # static config
            - ./static/traefik.toml:/etc/traefik/traefik.toml
