version: "3"

networks:
    traefik-octane-test-proxy:
        external: true

services:

    laravel-octane-roadrunner-php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: container-laravel-octane-roadrunner-php
        working_dir: /app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel-octane-roadrunner.rule=Host(`laravel-octane-roadrunner.local`)"
            - "traefik.http.routers.laravel-octane-roadrunner.entrypoints=http"
        tty: true
        networks:
            - traefik-octane-test-proxy
        expose:
            - 8000
        volumes:
            - ./:/app
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
