version: "3"

networks:
    traefik-octane-test-proxy:
        external: true
    lumen-nginx-network:

services:
    nginx:
        image: nginx:alpine
        container_name: lumen-nginx
        working_dir: /app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lumen-nginx.rule=Host(`lumen.local`)"
            - "traefik.http.routers.lumen-nginx.entrypoints=http"
        networks:
            - traefik-octane-test-proxy
            - lumen-nginx-network
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 777:80
        expose:
            - 80

    lumen-php-fpm-nginx:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: container-lumen-php-fpm-nginx
        working_dir: /app
        tty: true
        networks:
            - lumen-nginx-network
        expose:
            - 9000
        volumes:
            - ./:/app
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
